doc-warnings: no
test-warnings: no
strictness: medium
autodetect: yes
pylint:
    disable:
        - logging-too-many-args
        - too-many-function-args
        - unused-import

ignore-paths:
    - docs
    - pics
    - test

python-targets:
    - 2
