doc-warnings: no
test-warnings: no
strictness: medium
autodetect: yes
pylint:
    disable:
        - logging-too-many-args
        - too-many-function-args
        - unused-import
        - pointless-string-statement

ignore-paths:
    - docs
    - pics
    - test
    - pyxl320/__init__.py
    - pyxl320/DummySerial.py

python-targets:
    - 2
