language: python
sudo: false
python:
  - "2.7"
# command to install dependencies
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
# addons:
#     apt:
#         packages:
#             - pyserial
#             - nose
# install: pip install
install: pip install pyserial nose
# command to run tests
script: nosetests -v test/test.py
